"""Historical Native v6 offline falsification of signed shared support.

This script does not modify Taiji runtime state, topology or checkpoints.  It
listens to the real decoder-0 local writes made by M6 consolidation and mirrors
them into experimental banks with two changes only:

1. each cortical trace is represented as ON/OFF opponent activity around a
   waking-stream baseline, yielding a signed residual; and
2. every cortical coordinate has one fixed fan-out into a shared receptor bank,
   while every outcome row reads all bank channels.

The target is still generated by ``EpisodicField.replay``.  There is no event
list, teacher label, backward pass or write into the production substrate.
"""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from contextlib import contextmanager
from copy import deepcopy
from dataclasses import dataclass
import json
from pathlib import Path
import sys
from typing import DefaultDict, Dict, Iterable, List, Mapping, Sequence, Tuple

import torch

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SCRIPT_DIR = Path(__file__).resolve().parent
for path in (PROJECT_ROOT, SCRIPT_DIR):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from taiji import Taiji  # noqa: E402
from taiji.memory import EpisodicField  # noqa: E402
from taiji.sparse import SparseSynapses  # noqa: E402
from _diag_m6_margin import _probe_basis, _stream_baseline  # noqa: E402
from verify_taiji_m6_endogenous_replay import (  # noqa: E402
    OUTCOMES,
    SEED_PANEL,
    _config,
    _contingency,
    _episodes,
    _evaluate_contingency,
    _pretrain_corpus,
    _store,
)


@dataclass
class OpponentBank:
    """Fixed single-fan-out receptors plus one shared-support local decoder."""

    channels: torch.Tensor
    polarity: torch.Tensor
    group_scale: torch.Tensor
    weights: torch.Tensor
    max_weight_norm: float
    exposure: torch.Tensor
    plasticity_power: float

    @classmethod
    def create(
        cls,
        input_size: int,
        width: int,
        *,
        seed: int,
        max_weight_norm: float,
        plasticity_power: float = 0.0,
    ) -> "OpponentBank":
        if width <= 0 or width > input_size:
            raise ValueError("opponent width must be in [1, input_size]")
        generator = torch.Generator(device="cpu")
        generator.manual_seed(int(seed))
        permutation = torch.randperm(input_size, generator=generator)
        channels = torch.empty(input_size, dtype=torch.long)
        polarity = torch.empty(input_size, dtype=torch.float32)
        for rank, coordinate in enumerate(permutation.tolist()):
            channels[coordinate] = rank % width
            polarity[coordinate] = 1.0 if (rank // width) % 2 == 0 else -1.0
        counts = torch.bincount(channels, minlength=width).to(torch.float32)
        return cls(
            channels=channels,
            polarity=polarity,
            group_scale=counts.clamp_min(1.0).sqrt(),
            weights=torch.zeros(len(OUTCOMES), width),
            max_weight_norm=float(max_weight_norm),
            exposure=torch.zeros(width),
            plasticity_power=float(plasticity_power),
        )

    @property
    def width(self) -> int:
        return int(self.weights.shape[1])

    @property
    def receptor_edges(self) -> int:
        return int(self.channels.numel())

    @property
    def decoder_edges(self) -> int:
        return int(self.weights.numel())

    def encode(self, trace: torch.Tensor, baseline: torch.Tensor) -> torch.Tensor:
        residual = trace.detach().cpu() - baseline.detach().cpu()
        # Explicit dual rail.  The subtraction is written out rather than
        # returning ``residual`` so the diagnostic matches the proposed
        # substrate representation exactly: both rails are non-negative, while
        # their tied read is strictly signed and zero-sum.
        on = torch.relu(residual)
        off = torch.relu(-residual)
        signed = on - off
        context = torch.zeros(self.width)
        context.scatter_add_(0, self.channels, self.polarity * signed)
        return context / self.group_scale

    @torch.no_grad()
    def learn(
        self,
        trace: torch.Tensor,
        baseline: torch.Tensor,
        *,
        outcome: int,
        learning_rate: float,
        weight_decay: float,
    ) -> None:
        context = self.encode(trace, baseline)
        evidence = self.weights @ context
        target = torch.zeros(len(OUTCOMES))
        target[OUTCOMES.index(int(outcome))] = 1.0
        error = target - evidence
        scale = max(1.0, float((context != 0).sum().item()) ** 0.5)
        plastic_context = context
        if self.plasticity_power > 0.0:
            # A local familiarity resource.  Each receptor retains only its
            # accumulated share of sleep activity; the current population reads
            # the overlap with that field and broadcasts one metaplastic gain.
            # Repeated patterns therefore consume less of the bout's remaining
            # plasticity, while a distinct rare pattern still writes strongly.
            # No action label, event identity, quota or replay counter is used.
            energy = context.square()
            distribution = energy / energy.sum().clamp_min(1e-12)
            familiarity = torch.dot(self.exposure, distribution)
            gain = torch.exp(-self.plasticity_power * familiarity)
            plastic_context = gain * context
            self.exposure.add_(self.width * distribution)
        if weight_decay:
            self.weights.mul_(1.0 - float(weight_decay))
        self.weights.add_(
            float(learning_rate) * error.unsqueeze(1) * plastic_context.unsqueeze(0) / scale
        )
        norms = self.weights.norm(dim=1, keepdim=True).clamp_min(1e-12)
        self.weights.mul_(torch.clamp(self.max_weight_norm / norms, max=1.0))

    def evidence(self, traces: Iterable[torch.Tensor], baseline: torch.Tensor) -> torch.Tensor:
        return torch.stack([self.weights @ self.encode(trace, baseline) for trace in traces])


def _metrics(
    bank: OpponentBank,
    probes: Sequence[torch.Tensor],
    baseline: torch.Tensor,
    pairs: Mapping[int, int],
) -> Dict[str, object]:
    actions = sorted(pairs)
    evidence = bank.evidence(probes, baseline)
    margins = []
    correct = 0
    rows = []
    for row, action in enumerate(actions):
        target = OUTCOMES.index(int(pairs[action]))
        values = evidence[row]
        prediction = int(values.argmax().item())
        rivals = torch.cat([values[:target], values[target + 1 :]])
        margin = float((values[target] - rivals.max()).item())
        correct += int(prediction == target)
        margins.append(margin)
        rows.append(
            {
                "action": chr(action),
                "expected_outcome": chr(int(pairs[action])),
                "predicted_outcome": chr(OUTCOMES[prediction]),
                "margin": margin,
            }
        )
    return {
        "accuracy": correct / len(actions),
        "positive_margins": sum(value > 0.0 for value in margins),
        "pairs": len(actions),
        "mean_margin": sum(margins) / len(margins),
        "rows": rows,
    }


def _blank_copy(bank: OpponentBank) -> OpponentBank:
    copy = deepcopy(bank)
    copy.weights.zero_()
    copy.exposure.zero_()
    return copy


def _cosine(left: torch.Tensor, right: torch.Tensor) -> float:
    denominator = left.norm() * right.norm()
    if float(denominator.item()) <= 1e-12:
        return 0.0
    return float((torch.dot(left, right) / denominator).item())


def _alignment_geometry(
    bank: OpponentBank,
    records: Sequence[Tuple[int, int, torch.Tensor, float, float]],
    probes_by_action: Mapping[int, torch.Tensor],
    baseline: torch.Tensor,
) -> Dict[str, object]:
    """Measure whether endogenous sleep writes land on waking-readable axes."""

    grouped: DefaultDict[int, List[torch.Tensor]] = defaultdict(list)
    for action, _outcome, trace, _rate, _decay in records:
        grouped[int(action)].append(bank.encode(trace, baseline))

    actions = sorted(probes_by_action)
    probe_contexts = {action: bank.encode(probes_by_action[action], baseline) for action in actions}
    centroids = {
        action: torch.stack(grouped[action]).mean(dim=0) for action in actions if grouped[action]
    }
    cosine_rows = []
    for probe_action in actions:
        cosine_rows.append(
            {
                "probe_action": chr(probe_action),
                "against_write_centroids": {
                    chr(write_action): _cosine(
                        probe_contexts[probe_action], centroids[write_action]
                    )
                    for write_action in actions
                    if write_action in centroids
                },
            }
        )
    return {
        "write_counts_by_action": {chr(action): len(grouped[action]) for action in actions},
        "probe_to_write_centroid_cosines": cosine_rows,
    }


@contextmanager
def _mirror_real_replay_writes(
    model: Taiji,
    baseline: torch.Tensor,
    banks: Mapping[int, OpponentBank],
    lesions: Mapping[int, OpponentBank],
    resource_banks: Mapping[Tuple[int, float], OpponentBank],
    resource_lesions: Mapping[Tuple[int, float], OpponentBank],
    mode_banks: Mapping[Tuple[int, float], OpponentBank],
    mode_lesions: Mapping[Tuple[int, float], OpponentBank],
    sleep_homeostasis_rate: float,
):
    """Mirror decoder-0 writes; the production consolidation remains untouched."""

    original_replay = EpisodicField.replay
    original_update = SparseSynapses.local_update
    decoder = model.fabric.decoders[0]
    state = {
        "action": None,
        "outcome": None,
        "writes": 0,
        "accepted_pairs": Counter(),
        "records": [],
        "sleep_threshold_offset": torch.zeros(model.config.memory_units),
        "mode_resources": {key: torch.ones(model.config.alphabet_size) for key in mode_banks},
        "mode_gains": {},
    }

    def replay(self, memory_state, *, tick, generator):
        replay_state = memory_state
        if sleep_homeostasis_rate > 0.0:
            replay_state = memory_state.clone()
            replay_state.threshold.add_(state["sleep_threshold_offset"])
        next_state, result = original_replay(
            self,
            replay_state,
            tick=tick,
            generator=generator,
        )
        if sleep_homeostasis_rate > 0.0:
            # A separate slow sleep-only intrinsic set point.  Frequently used
            # memory units become temporarily less excitable across the whole
            # bout, not just for the next few replays.  The zero-mean update
            # preserves overall field excitability, and the waking threshold is
            # restored before returning, so no sleep artefact enters checkpoint.
            active = (result.pattern > 1e-6).to(torch.float32)
            state["sleep_threshold_offset"].add_(
                float(sleep_homeostasis_rate) * (active - active.mean())
            )
            next_state.threshold.copy_(memory_state.threshold)
        if result.accepted:
            action = int(result.action_probabilities.argmax().item())
            outcome = int(result.outcome_probabilities.argmax().item())
            state["action"] = action
            state["outcome"] = outcome
            state["accepted_pairs"][(action, outcome)] += 1
            for key in mode_banks:
                retention = float(key[1])
                resource = state["mode_resources"][key]
                state["mode_gains"][key] = float(resource[action].item())
                resource[action].mul_(retention)
        else:
            state["action"] = None
            state["outcome"] = None
            state["mode_gains"].clear()
        return next_state, result

    def local_update(
        self,
        postsynaptic_error,
        presynaptic_trace,
        *,
        learning_rate,
        weight_decay,
    ):
        if self is decoder and state["outcome"] is not None:
            action = int(state["action"])
            outcome = int(state["outcome"])
            lesion = OUTCOMES[(OUTCOMES.index(outcome) + 1) % len(OUTCOMES)]
            for width, bank in banks.items():
                bank.learn(
                    presynaptic_trace,
                    baseline,
                    outcome=outcome,
                    learning_rate=learning_rate,
                    weight_decay=weight_decay,
                )
                lesions[width].learn(
                    presynaptic_trace,
                    baseline,
                    outcome=lesion,
                    learning_rate=learning_rate,
                    weight_decay=weight_decay,
                )
            for key, bank in resource_banks.items():
                bank.learn(
                    presynaptic_trace,
                    baseline,
                    outcome=outcome,
                    learning_rate=learning_rate,
                    weight_decay=weight_decay,
                )
                resource_lesions[key].learn(
                    presynaptic_trace,
                    baseline,
                    outcome=lesion,
                    learning_rate=learning_rate,
                    weight_decay=weight_decay,
                )
            for key, bank in mode_banks.items():
                mode_rate = float(learning_rate) * float(state["mode_gains"][key])
                bank.learn(
                    presynaptic_trace,
                    baseline,
                    outcome=outcome,
                    learning_rate=mode_rate,
                    weight_decay=weight_decay,
                )
                mode_lesions[key].learn(
                    presynaptic_trace,
                    baseline,
                    outcome=lesion,
                    learning_rate=mode_rate,
                    weight_decay=weight_decay,
                )
            state["records"].append(
                (
                    action,
                    outcome,
                    presynaptic_trace.detach().cpu().clone(),
                    float(learning_rate),
                    float(weight_decay),
                )
            )
            state["writes"] += 1
        return original_update(
            self,
            postsynaptic_error,
            presynaptic_trace,
            learning_rate=learning_rate,
            weight_decay=weight_decay,
        )

    EpisodicField.replay = replay
    SparseSynapses.local_update = local_update
    try:
        yield state
    finally:
        SparseSynapses.local_update = original_update
        EpisodicField.replay = original_replay


def run_seed(
    seed: int,
    *,
    cycles: int,
    widths: Sequence[int],
    resource_powers: Sequence[float],
    sleep_trace_decay: float | None,
    sleep_fatigue_gain: float | None,
    sleep_homeostasis_rate: float,
    mode_resource_retentions: Sequence[float],
) -> Dict[str, object]:
    model = Taiji(_config(seed), episode_id="opponent-bootstrap")
    model.learn_bytes(_pretrain_corpus(), epochs=6)
    episodes = _episodes()
    pairs = _contingency(episodes)
    _store(model, episodes)
    stored = model.checkpoint()
    baseline = _stream_baseline(stored, ticks=256)

    banks = {
        width: OpponentBank.create(
            model.config.region_sizes[0],
            width,
            seed=seed * 1009 + width,
            max_weight_norm=model.config.max_weight_norm,
        )
        for width in widths
    }
    lesions = {width: deepcopy(bank) for width, bank in banks.items()}
    resource_banks = {
        (width, power): OpponentBank.create(
            model.config.region_sizes[0],
            width,
            seed=seed * 1009 + width,
            max_weight_norm=model.config.max_weight_norm,
            plasticity_power=power,
        )
        for width in widths
        for power in resource_powers
    }
    resource_lesions = {key: deepcopy(bank) for key, bank in resource_banks.items()}
    mode_banks = {
        (width, retention): OpponentBank.create(
            model.config.region_sizes[0],
            width,
            seed=seed * 1009 + width,
            max_weight_norm=model.config.max_weight_norm,
        )
        for width in widths
        for retention in mode_resource_retentions
    }
    mode_lesions = {key: deepcopy(bank) for key, bank in mode_banks.items()}

    sleep_checkpoint = deepcopy(stored)
    if sleep_trace_decay is not None:
        sleep_checkpoint["config"]["memory_trace_decay"] = float(sleep_trace_decay)
    if sleep_fatigue_gain is not None:
        sleep_checkpoint["config"]["replay_fatigue_gain"] = float(sleep_fatigue_gain)
    sleeper = Taiji.from_checkpoint(sleep_checkpoint)
    sleeper.reset_dynamics(episode_id="opponent-sleep")
    with _mirror_real_replay_writes(
        sleeper,
        baseline,
        banks,
        lesions,
        resource_banks,
        resource_lesions,
        mode_banks,
        mode_lesions,
        sleep_homeostasis_rate,
    ) as captured:
        consolidation = sleeper.consolidate(cycles=cycles, learn=True)
    rested = sleeper.checkpoint()
    actions = sorted(pairs)
    probes_by_action = {action: _probe_basis(rested, action) for action in actions}
    probes = [probes_by_action[action] for action in actions]
    records = list(captured["records"])

    # Two diagnostic controls isolate the remaining failure without touching
    # production state.  ``probe_aligned`` preserves every endogenous replay
    # target, rate and count but writes it on the waking basis for the recalled
    # action.  ``balanced_probe_aligned`` additionally gives every action the
    # same number of writes, using the minimum naturally available count.
    probe_aligned = {width: _blank_copy(bank) for width, bank in banks.items()}
    balanced_probe_aligned = {width: _blank_copy(bank) for width, bank in banks.items()}
    for action, outcome, _trace, rate, decay in records:
        for bank in probe_aligned.values():
            bank.learn(
                probes_by_action[action],
                baseline,
                outcome=outcome,
                learning_rate=rate,
                weight_decay=decay,
            )

    records_by_action: DefaultDict[int, List[Tuple[int, int, torch.Tensor, float, float]]] = (
        defaultdict(list)
    )
    for record in records:
        records_by_action[int(record[0])].append(record)
    balanced_writes = min((len(records_by_action[action]) for action in actions), default=0)
    for index in range(balanced_writes):
        for action in actions:
            _record_action, outcome, _trace, rate, decay = records_by_action[action][index]
            for bank in balanced_probe_aligned.values():
                bank.learn(
                    probes_by_action[action],
                    baseline,
                    outcome=outcome,
                    learning_rate=rate,
                    weight_decay=decay,
                )

    actual = _evaluate_contingency(rested, pairs)
    variants = {}
    for width in widths:
        metrics = _metrics(banks[width], probes, baseline, pairs)
        lesion_metrics = _metrics(lesions[width], probes, baseline, pairs)
        probe_aligned_metrics = _metrics(probe_aligned[width], probes, baseline, pairs)
        balanced_metrics = _metrics(balanced_probe_aligned[width], probes, baseline, pairs)
        variants[str(width)] = {
            **metrics,
            "probe_aligned_positive_margins": probe_aligned_metrics["positive_margins"],
            "probe_aligned_rows": probe_aligned_metrics["rows"],
            "balanced_probe_aligned_positive_margins": balanced_metrics["positive_margins"],
            "balanced_probe_aligned_rows": balanced_metrics["rows"],
            "rotated_content_lesion_accuracy": lesion_metrics["accuracy"],
            "rotated_content_lesion_positive_margins": lesion_metrics["positive_margins"],
            "receptor_edges": banks[width].receptor_edges,
            "decoder_edges_for_four_outcomes": banks[width].decoder_edges,
            "alignment": _alignment_geometry(banks[width], records, probes_by_action, baseline),
            "local_resource": {
                str(power): {
                    **_metrics(resource_banks[(width, power)], probes, baseline, pairs),
                    "rotated_content_lesion_positive_margins": _metrics(
                        resource_lesions[(width, power)],
                        probes,
                        baseline,
                        pairs,
                    )["positive_margins"],
                }
                for power in resource_powers
            },
            "winner_resource": {
                str(retention): {
                    **_metrics(mode_banks[(width, retention)], probes, baseline, pairs),
                    "rotated_content_lesion_positive_margins": _metrics(
                        mode_lesions[(width, retention)],
                        probes,
                        baseline,
                        pairs,
                    )["positive_margins"],
                }
                for retention in mode_resource_retentions
            },
        }
    accepted_pairs = {
        f"{chr(action)}->{chr(outcome)}": count
        for (action, outcome), count in sorted(captured["accepted_pairs"].items())
    }
    return {
        "seed": seed,
        "accepted_replays": consolidation.accepted,
        "mirrored_local_writes": int(captured["writes"]),
        "accepted_pairs": accepted_pairs,
        "balanced_writes_per_action": balanced_writes,
        "sleep_trace_decay": sleeper.config.memory_trace_decay,
        "sleep_fatigue_gain": sleeper.config.replay_fatigue_gain,
        "sleep_homeostasis_rate": float(sleep_homeostasis_rate),
        "sleep_threshold_offset_norm": float(captured["sleep_threshold_offset"].norm().item()),
        "baseline_norm": float(baseline.norm().item()),
        "actual_taiji_accuracy": actual["contingency_accuracy"],
        "actual_taiji_positive_margins": sum(float(row["margin"]) > 0.0 for row in actual["rows"]),
        "variants": variants,
    }


def run_panel(
    seeds: Sequence[int],
    *,
    cycles: int,
    widths: Sequence[int],
    resource_powers: Sequence[float],
    sleep_trace_decay: float | None,
    sleep_fatigue_gain: float | None,
    sleep_homeostasis_rate: float,
    mode_resource_retentions: Sequence[float],
) -> Dict[str, object]:
    rows = []
    for seed in seeds:
        result = run_seed(
            seed,
            cycles=cycles,
            widths=widths,
            resource_powers=resource_powers,
            sleep_trace_decay=sleep_trace_decay,
            sleep_fatigue_gain=sleep_fatigue_gain,
            sleep_homeostasis_rate=sleep_homeostasis_rate,
            mode_resource_retentions=mode_resource_retentions,
        )
        rows.append(result)
        cells = "  ".join(
            f"K{width}={result['variants'][str(width)]['positive_margins']}/4"
            f"|P{result['variants'][str(width)]['probe_aligned_positive_margins']}"
            f"|B{result['variants'][str(width)]['balanced_probe_aligned_positive_margins']}"
            for width in widths
        )
        print(
            f"seed {seed:3d}  actual={result['actual_taiji_positive_margins']}/4"
            f"  {cells}  writes={result['mirrored_local_writes']}",
            flush=True,
        )

    summary = {}
    for width in widths:
        key = str(width)
        passing = sum(int(row["variants"][key]["positive_margins"] == 4) for row in rows)
        lesion_passing = sum(
            int(row["variants"][key]["rotated_content_lesion_positive_margins"] == 4)
            for row in rows
        )
        summary[key] = {
            "passing_seeds": passing,
            "seed_count": len(rows),
            "all_seeds_pass": passing == len(rows),
            "rotated_content_lesion_passing_seeds": lesion_passing,
            "probe_aligned_passing_seeds": sum(
                int(row["variants"][key]["probe_aligned_positive_margins"] == 4) for row in rows
            ),
            "balanced_probe_aligned_passing_seeds": sum(
                int(row["variants"][key]["balanced_probe_aligned_positive_margins"] == 4)
                for row in rows
            ),
            "local_resource": {
                str(power): {
                    "passing_seeds": sum(
                        int(
                            row["variants"][key]["local_resource"][str(power)]["positive_margins"]
                            == 4
                        )
                        for row in rows
                    ),
                    "rotated_content_lesion_passing_seeds": sum(
                        int(
                            row["variants"][key]["local_resource"][str(power)][
                                "rotated_content_lesion_positive_margins"
                            ]
                            == 4
                        )
                        for row in rows
                    ),
                }
                for power in resource_powers
            },
            "winner_resource": {
                str(retention): {
                    "passing_seeds": (
                        winner_passing := sum(
                            int(
                                row["variants"][key]["winner_resource"][str(retention)][
                                    "positive_margins"
                                ]
                                == 4
                            )
                            for row in rows
                        )
                    ),
                    "rotated_content_lesion_passing_seeds": (
                        winner_lesion_passing := sum(
                            int(
                                row["variants"][key]["winner_resource"][str(retention)][
                                    "rotated_content_lesion_positive_margins"
                                ]
                                == 4
                            )
                            for row in rows
                        )
                    ),
                    "all_seeds_pass": (winner_passing == len(rows) and winner_lesion_passing == 0),
                    "minimum_margin": min(
                        float(pair["margin"])
                        for row in rows
                        for pair in row["variants"][key]["winner_resource"][str(retention)]["rows"]
                    ),
                    "mean_margin": sum(
                        float(pair["margin"])
                        for row in rows
                        for pair in row["variants"][key]["winner_resource"][str(retention)]["rows"]
                    )
                    / sum(
                        len(row["variants"][key]["winner_resource"][str(retention)]["rows"])
                        for row in rows
                    ),
                }
                for retention in mode_resource_retentions
            },
        }
    candidates = [
        {
            "width": int(width),
            "winner_resource_retention": float(retention),
            **summary[str(width)]["winner_resource"][str(retention)],
        }
        for width in widths
        for retention in mode_resource_retentions
        if summary[str(width)]["winner_resource"][str(retention)]["all_seeds_pass"]
    ]
    selected = max(candidates, key=lambda row: row["minimum_margin"]) if candidates else None
    return {
        "benchmark": "taiji-signed-opponent-offline",
        "status": "pass" if selected is not None else "fail",
        "cycles": cycles,
        "seeds": list(seeds),
        "widths": list(widths),
        "resource_powers": list(resource_powers),
        "sleep_trace_decay_override": sleep_trace_decay,
        "sleep_fatigue_gain_override": sleep_fatigue_gain,
        "sleep_homeostasis_rate": float(sleep_homeostasis_rate),
        "mode_resource_retentions": list(mode_resource_retentions),
        "constraints": {
            "runtime_modified": False,
            "external_replay_list": False,
            "teacher_target": False,
            "target_source": "episodic field replay outcome mode",
            "diagnostic_controls_use_only_endogenous_replay_modes": True,
            "one_fixed_receptor_edge_per_cortical_coordinate": True,
            "all_outcome_rows_share_channel_support": True,
            "strict_on_off_opponent_read": True,
            "local_resource_uses_event_identity_or_quota": False,
            "sleep_homeostasis_uses_event_identity_or_quota": False,
            "sleep_homeostasis_persists_into_waking_state": False,
            "winner_resource_uses_external_event_identity_or_quota": False,
        },
        "selected_candidate": selected,
        "per_seed": rows,
        "summary": summary,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cycles", type=int, default=96)
    parser.add_argument("--widths", type=int, nargs="+", default=[64])
    parser.add_argument("--resource-powers", type=float, nargs="+", default=[0.0])
    parser.add_argument("--sleep-trace-decay", type=float)
    parser.add_argument("--sleep-fatigue-gain", type=float)
    parser.add_argument("--sleep-homeostasis-rate", type=float, default=0.0)
    parser.add_argument(
        "--mode-resource-retentions",
        type=float,
        nargs="+",
        default=[0.5, 0.7, 0.8, 0.9],
    )
    parser.add_argument("--seeds", type=int, nargs="+", default=list(SEED_PANEL))
    parser.add_argument(
        "--output",
        type=Path,
        default=PROJECT_ROOT / "reports" / "taiji_signed_opponent_20260822.json",
    )
    args = parser.parse_args()
    report = run_panel(
        tuple(args.seeds),
        cycles=int(args.cycles),
        widths=tuple(dict.fromkeys(int(width) for width in args.widths)),
        resource_powers=tuple(dict.fromkeys(float(power) for power in args.resource_powers)),
        sleep_trace_decay=args.sleep_trace_decay,
        sleep_fatigue_gain=args.sleep_fatigue_gain,
        sleep_homeostasis_rate=float(args.sleep_homeostasis_rate),
        mode_resource_retentions=tuple(
            dict.fromkeys(float(value) for value in args.mode_resource_retentions)
        ),
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"status={report['status']}  report={args.output}")
    return 0 if report["status"] == "pass" else 1


if __name__ == "__main__":
    raise SystemExit(main())
