"""Taiji: a native persistent predictive-computing architecture.

This top-level package is independent of the legacy NeuroPlex Transformer
runtime.  PyTorch is used only as a tensor execution engine.
"""

from .adapter import TSKV8Adapter
from .assembly_evaluation import (
    AssemblyRelationEvaluationConfig,
    AssemblyRelationEvaluator,
)
from .assembly_relations import AssemblyRelationCorpus, AssemblyRelationExample
from .config import CapacityPolicy, PerceptionConfig, TaijiConfig
from .contracts import (
    CONTRACT_FORMAT,
    CONTRACT_VERSION,
    ActionIntent,
    CognitiveState,
    DevelopmentState,
    EpisodicMemoryRecord,
    Goal,
    GoalState,
    HomeostaticState,
    LearningState,
    NativeCheckpoint,
    Observation,
    Outcome,
    PerceptEvent,
    PlanCandidate,
    PlanState,
    SelfState,
    WorkingMemoryItem,
    WorkspaceCandidate,
    WorkspaceSelection,
    WorkspaceState,
    WorldAction,
    WorldAffordance,
    WorldEpisode,
    WorldEpisodeCorpus,
    WorldEvent,
    WorldInterventionCase,
    WorldInterventionCorpus,
    WorldObject,
    WorldPredictionRecord,
    WorldState,
    WorldTransition,
)
from .contracts import MemoryState as NativeMemoryState
from .environment import EnvironmentOutcome, TaijiEnvironment
from .episodic_memory import (
    EPISODIC_MEMORY_CHECKPOINT_FORMAT,
    EpisodicMemoryHit,
    EpisodicMemoryStore,
)
from .evaluation import A1EvaluationConfig, PerceptionCorpus, PerceptionEvaluator
from .fabric import TaijiFabric
from .homeostasis import (
    HOMEOSTASIS_CHECKPOINT_FORMAT,
    HomeostaticConfig,
    HomeostaticController,
    HomeostaticDrive,
)
from .memory import EpisodicField, EpisodicReplay, EpisodicWrite
from .model import Taiji
from .organs import ByteMotor, ByteSensor, SparseReceptorBank
from .perception import LearnedPerception
from .planning import (
    PLANNING_CHECKPOINT_FORMAT,
    GoalPlanner,
    ImaginedRollout,
    PlanningCandidate,
    PlanningConfig,
    PlanningDecision,
    RolloutDecision,
)
from .procedural_memory import (
    PROCEDURAL_MEMORY_CHECKPOINT_FORMAT,
    SEQUENTIAL_PROCEDURAL_MEMORY_CHECKPOINT_FORMAT,
    ProceduralMemoryLearner,
    ProceduralSequenceLearner,
)
from .semantic_memory import (
    SEMANTIC_MEMORY_CHECKPOINT_FORMAT,
    SemanticMemoryLearner,
)
from .sparse import SparseSynapses
from .state import (
    MemoryRecall,
    MemoryState,
    PendingAction,
    PendingExperience,
    RegionState,
    TaijiConsolidation,
    TaijiDecision,
    TaijiOutcome,
    TaijiState,
    TaijiStep,
)
from .workspace import (
    WorkspaceCollaborationEvaluator,
    WorkspaceCompositionSample,
    WorkspaceRouter,
    WorkspaceRoutingExample,
)
from .world import WORLD_STATE_CHECKPOINT_FORMAT, TaijiWorldState
from .world_learning import (
    WorldDynamicsLearner,
    WorldEpisodeEvaluationConfig,
    WorldEpisodeEvaluator,
    WorldEpisodeRollout,
    WorldInterventionEvaluationConfig,
    WorldInterventionEvaluator,
    WorldPrediction,
    WorldSchema,
)

__all__ = [
    "ByteMotor",
    "ByteSensor",
    "ActionIntent",
    "A1EvaluationConfig",
    "AssemblyRelationCorpus",
    "AssemblyRelationExample",
    "AssemblyRelationEvaluationConfig",
    "AssemblyRelationEvaluator",
    "CapacityPolicy",
    "CognitiveState",
    "CONTRACT_FORMAT",
    "CONTRACT_VERSION",
    "DevelopmentState",
    "EnvironmentOutcome",
    "EpisodicMemoryHit",
    "EpisodicMemoryRecord",
    "EpisodicMemoryStore",
    "EPISODIC_MEMORY_CHECKPOINT_FORMAT",
    "EpisodicField",
    "EpisodicReplay",
    "EpisodicWrite",
    "MemoryRecall",
    "MemoryState",
    "NativeCheckpoint",
    "NativeMemoryState",
    "Observation",
    "Outcome",
    "PerceptionConfig",
    "PerceptionCorpus",
    "PerceptionEvaluator",
    "PerceptEvent",
    "GoalPlanner",
    "ImaginedRollout",
    "PlanningCandidate",
    "PlanningConfig",
    "PlanningDecision",
    "RolloutDecision",
    "PLANNING_CHECKPOINT_FORMAT",
    "ProceduralMemoryLearner",
    "PROCEDURAL_MEMORY_CHECKPOINT_FORMAT",
    "ProceduralSequenceLearner",
    "SEQUENTIAL_PROCEDURAL_MEMORY_CHECKPOINT_FORMAT",
    "PlanCandidate",
    "PlanState",
    "PendingAction",
    "PendingExperience",
    "RegionState",
    "SparseReceptorBank",
    "SparseSynapses",
    "SemanticMemoryLearner",
    "SEMANTIC_MEMORY_CHECKPOINT_FORMAT",
    "Taiji",
    "TaijiConfig",
    "TaijiConsolidation",
    "TaijiDecision",
    "TaijiEnvironment",
    "TaijiFabric",
    "TaijiOutcome",
    "TaijiState",
    "TaijiStep",
    "TSKV8Adapter",
    "Goal",
    "GoalState",
    "HomeostaticState",
    "HomeostaticConfig",
    "HomeostaticController",
    "HomeostaticDrive",
    "HOMEOSTASIS_CHECKPOINT_FORMAT",
    "LearningState",
    "LearnedPerception",
    "SelfState",
    "WorkspaceState",
    "WorkspaceCandidate",
    "WorkspaceSelection",
    "WorkspaceRouter",
    "WorkspaceRoutingExample",
    "WorkspaceCompositionSample",
    "WorkspaceCollaborationEvaluator",
    "WorkingMemoryItem",
    "WorldState",
    "WorldAction",
    "WorldAffordance",
    "WorldEvent",
    "WorldInterventionCase",
    "WorldInterventionCorpus",
    "WorldEpisode",
    "WorldEpisodeCorpus",
    "WorldObject",
    "WorldPredictionRecord",
    "WorldTransition",
    "TaijiWorldState",
    "WORLD_STATE_CHECKPOINT_FORMAT",
    "WorldDynamicsLearner",
    "WorldEpisodeEvaluationConfig",
    "WorldEpisodeEvaluator",
    "WorldEpisodeRollout",
    "WorldInterventionEvaluationConfig",
    "WorldInterventionEvaluator",
    "WorldPrediction",
    "WorldSchema",
]
